### ISSUE TITLE
Self-healing applications with Ansible

### ISSUE THREAD

**Issue by jetzlstorfer** [ansible-community/ansible-london-meetup#10]
## Talk Description
Successfully operating and maintaining large-scale microservices infrastructures is a huge challenge for developers as well as operations. In case of failures of the software or infrastructure, the system must be brought up again quickly, since time is most often the crucial factor. However, manual inspection and analysis of failures for mitigation is often cumbersome and slow. Thus, automation for remediation is needed. 

In this session we will explore how to leverage Ansible as automation platform to automate remediation tasks. Upon of this, we will learn what is needed to build your own remediation workflow including monitoring, automation and orchestration tools to setup and control your remediation actions. 

## Estimated Duration
30 minutes

## Twitter Handle

@jetzlstorfer

**Comment by gundalow** [comment]
@jetzlstorfer thank you. Once we have dates confirmed for 2019 we will be in contact.

Hope to see you at out December meetup.

**Comment by gundalow** [comment]
Hi,
Would you be available to present on **Thursday 31st January** as part of https://www.meetup.com/Ansible-London/events/257896565/ ?

**Comment by jetzlstorfer** [comment]
Unfortunately this date is not possible for me, since I am travelling for another event.

**Comment by Shaps** [comment]
Hi @jetzlstorfer, 
No worries. We are planning a new one in March, hopefully you'll make it for that one :+1:

**Comment by gundalow** [comment]
Hi,
The next meetup is Tuesday 19th March https://www.meetup.com/Ansible-London/events/258726000/
Does this date work for you? If not we will have another meetup a few months after.

**Comment by jetzlstorfer** [comment]
Hi @gundalow 
thanks for reaching out. I'm sorry this date is again not possible since I'm travelling.
Hope to make it for the next event! :)
Cheers

**Comment by gundalow** [comment]
@jetzlstorfer next time :)
As an aside, do you know how else we should promote/improve the meetup? All feedback is welcome. Feel free to email me direct gundalow at redhat dot com.

**Comment by gundalow** [comment]
Hi,
I've just scheduled our next meetup on [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) would you be available to present then?

**Comment by jetzlstorfer** [comment]
@gundalow 
Yes, that would be possible for me. Would be happy to present!

**Comment by gundalow** [comment]
@jetzlstorfer Thank you. I've added you to the agenda.
We'd appreciate your help promoting the event

**Comment by jetzlstorfer** [comment]
@gundalow Am I assuming correctly that the speaking slots are about 30mins?

**Comment by Shaps** [comment]
Hi @jetzlstorfer Thanks for the talk! We have now added the directory for the meetup [here](https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-06-13), if you want to share the slides, feel free to raise a PR!
