### ISSUE TITLE
How I use Ansible to save me 30 minutes a day - Network Engineer 

### ISSUE THREAD

**Issue by rogerperkin** [ansible-community/ansible-london-meetup#11]
## Talk Title 
How I use Ansible to save me 30 minutes a day as a Network Consultant

## Talk Description 
As a network consultant I am always staging new environments and working on new networks every week. Ansible makes my initial audit of a new customer network very easy, and has also saved me hours and hours when staging new environments. 

## Talk Duration 
This talk will last between 5-10 minutes 

## Twitter 
@rogernperkin
<!-- So we can promote the talk, can we know your twitter handle? --!>

**Comment by gundalow** [comment]
@rogerperkin Thanks, I'll be in contact once we've got 2019 dates organised.

**Comment by gundalow** [comment]
Hi,
Would you be available to present on **Thursday 31st January** as part of https://www.meetup.com/Ansible-London/events/257896565/ ?

**Comment by rogerperkin** [comment]
Hi, yes that will be great

**Comment by rogerperkin** [comment]
how long do I have?

**Comment by Shaps** [comment]
Hi @rogerperkin,
I'd say around 15/20 min

**Comment by rogerperkin** [comment]
Ok will prepare for 15-20 minutes - thanks

**Comment by gundalow** [comment]
@rogerperkin  Once again thank you for your presentation. I heard really good feedback from people.
I've created https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-01-31 Feel free to raise a PR to update that as you see fit, add links.

**Comment by gundalow** [comment]
Slides added to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-01-31

Thanks again!
