### ISSUE TITLE
Bringing ansible to an existing ops infrastructure

### ISSUE THREAD

**Issue by michaelkaye** [ansible-community/ansible-london-meetup#14]
## Talk title
Bringing ansible to an existing ops infrastructure

## Talk Description
Mainly discussing approaches I've taken to adopt ansible within matrix.org, describing where we started, what worked, what ran into problems. I'll cover four or five strategies I tried.

## Estimated Duration
Up to 30 min, but I can exclude some of the things I tried to change the length if we need to fit a shorter length.

## Twitter Handle
michael from @matrixdotorg
<!-- So we can promote the talk, can we know your twitter handle? --!>

**Comment by gundalow** [comment]
@michaelkaye Thank you for creating this. Was good to chat with you during the December meetup. Once we've decided on 2019 dates we will be in contact.

**Comment by gundalow** [comment]
Hi,
Would you be available to present on **Thursday 31st January** as part of https://www.meetup.com/Ansible-London/events/257896565/ ?

**Comment by michaelkaye** [comment]
@gundalow Hi there,

Yes, that should be fine. Is 30min still a reasonable target?

**Comment by Shaps** [comment]
Hi @michaelkaye, 
Yes, I believe 30 min should be a reasonable time.

**Comment by gundalow** [comment]
@michaelkaye Once again thank you for your presentation. I heard really good feedback from people.
I've created https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-01-31 Feel free to raise a PR to update that as you see fit, add links

If your presentation is online anyway linking to that would be great, or perhaps turn into pptx/pdf and raise a PR to add that there. See [example](https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2018-12-12)

**Comment by gundalow** [comment]
Slides added to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-01-31

Thanks again!
