### ISSUE TITLE
Data Deployments with Ansible

### ISSUE THREAD

**Issue by pmajmudar** [ansible-community/ansible-london-meetup#15]
## Talk title
Data Deployments with Ansible

## Talk Description
Growth Intelligence is building a platform to help business grow faster and connect to their customers using AI. 
We deploy machine learning models into a web app backed by data on millions of UK businesses. In this talk I will talk about how we also use Ansible to deploy the data our machine learning models rely on and describe how we use Ansible roles and playbooks to snapshot / restore Elasticsearch indices into our staging and prod environments. 

## Estimated Duration
10-15 minutes

## Twitter Handle
@prashmaj

**Comment by gundalow** [comment]
@pmajmudar Hi, thank you for the proposal for this talk, sounds really interesting.
We already have all the talks lined up for January. We will be looking at March for the next meetup, Once the date is confirmed we will reply to this message and see if that works for you.

**Comment by Shaps** [comment]
Hi @pmajmudar,
Thanks for submitting this. Is by any chance your company willing to sponsor a meetup?

**Comment by gundalow** [comment]
Hi,
The next meetup is Tuesday 19th March https://www.meetup.com/Ansible-London/events/258726000/
Does this date work for you? If not we will have another meetup a few months after.

**Comment by pmajmudar** [comment]
Hi @gundalow Tuesday 19th March works for me - happy to present on "Data Deployments with Ansible" 

I don't think we're in a position to sponsor however - thanks

Prash

**Comment by gundalow** [comment]
Hi
Looking forward to your presentation tomorrow. When you arrive (around 6pm) please come and find me so we can get you setup with a microphone.

If you haven't connected to Sainsbury's WiFi before I suggest you do that from reception (ground floor) as you need an SMS code as the auditorium is in the basement and you may not have mobile reception.

**Comment by pmajmudar** [comment]
@gundalow That's great - can I just confirm how long the speaking slot I have is? Will it include questions at the end?
In terms of presentation - should I email you my slides or bring them on USB?

**Comment by gundalow** [comment]
Hi,
Generally presenters use their own laptop.
I believe we've allocated 15 minutes including Q&A, though we generally have a bit of flexibility in the schedule.

**Comment by gundalow** [comment]
@pmajmudar Thank you for your presentation yesterday.

Would you be happy to share your slides? If they are online already please let me know the link, otherwise could you please raise a PR to add them to https://github.com/ansible-community/ansible-london-meetup/blob/master/presentations/

**Comment by gundalow** [comment]
@pmajmudar Hi, would you be happy to share your slides?

**Comment by gundalow** [comment]
Not got any slides, so going to close this. Feel free to raise a pull request to add them to https://github.com/ansible-community/ansible-london-meetup/blob/master/presentations/ in the future
