### ISSUE TITLE
Automate Kubernetes Workloads with Ansible

### ISSUE THREAD

**Issue by mhrivnak** [ansible-community/ansible-london-meetup#16]
## Talk title
Automate Kubernetes Workloads with Ansible

## Talk Description
Ansible's `k8s` module makes it easier than ever to automate a Kubernetes cluster, even for someone who has little Ansible experience. This talk introduces the `k8s` module and shows how it can be used to define and distribute an application for self-service provisioning. We will conclude by learning how to achieve day-two management by making an Ansible-based Operator.

## Estimated Duration
15 minutes

## Twitter Handle
@michael_hrivnak

**Comment by mhrivnak** [comment]
Since I do not live in London, I am specifically available for the January 31 meeting.

**Comment by gundalow** [comment]
@mhrivnak Thank you for the offer. I think we've managed to tweak the schedule so we can fit you in.

**Comment by mhrivnak** [comment]
Thank you! I'm looking forward to it.

**Comment by gundalow** [comment]
@mhrivnak Random request, if I gave you some Ansible stickers tomorrow would you possibly be able to take them to FOSDEM to give to Robyn Bergeron or Carol Chen? Apparently, we have a logistics SNAFU and the swag hasn't arrived for FOSDEM/cfgmgmtcamp.

**Comment by mhrivnak** [comment]
Sure thing. Happy to help.

**Comment by gundalow** [comment]
@mhrivnak Once again thank you for your presentation. I heard really good feedback from people.
I've created https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-01-31 Feel free to raise a PR to update that as you see fit, add links

If your presentation is online anyway linking to that would be great, or perhaps turn into pptx/pdf and raise a PR to add that there. See [example](https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2018-12-12)
