### ISSUE TITLE
Ansible Day to Day usecase

### ISSUE THREAD

**Issue by deepaklor** [ansible-community/ansible-london-meetup#17]
## Twitter Handle
<!-- So we can promote the talk, can we know your twitter handle? --!>
https://twitter.com/deepaklor

**Comment by deepaklor** [comment]
# Tasks 
Planning to discuss on the below topics at High level and should be able to answer any query regarding the day to day implementation and usage by Ansible.

1. Stop all applications/linux services  and modify configuration globally.
2. Example modify the database LoadBalancer IP used by the application configuration and restart all nodes.
3. Take a backup of application configuration before doing the change.
4. How to get the results of the all the application servers , example if you want the last few lines of the application log of all servers may be 50-500 and even more.
5. how to check any for a given server may be disk space,RAM etc with out login to any server using Ansible Adhoc.

**Comment by deepaklor** [comment]
**
How to ansible for deployments and for all day to day tasks!!!!!!!!!
**

**Comment by deepaklor** [comment]
# Simple Playbook Example, How to use documentation to achieve the goal or business requirement.
$ cat abc.yml 
---
- name: myfirst learning plays
  hosts:  dev
  become: yes
  gather_facts: False
  tasks:
    - name: task to update configuration file
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: 'Listen 9090'
        backup: yes
...

**Comment by deepaklor** [comment]
# Playbook to stop a service , update configuration file and start the service back,

---
- name: myfirstplay
  hosts:  dev
  become: yes
  tasks:
    - name: task to stop services
      service:
        name: httpd
        state: stopped

    - name: task to update configuration file
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: 'Listen 80'
        backup: yes

    - name: task to start service
      service:
        name: httpd
        state: started
...

**Comment by deepaklor** [comment]
#Example of an ADHOC command usage,
$ ansible dev -m shell -a "systemctl status httpd -l"

**Comment by deepaklor** [comment]
$ ansible dev -m service -a "name=httpd state=started" -b

**Comment by deepaklor** [comment]
# How to stop multiple services, Example playbook

--
- name: mysecond learning plays
  hosts:  dev
  become: yes
  gather_facts: True
  tasks:
    - name: task to stop all services as per given list
      service:
        name: "{{  item  }}"
        state:  started
      with_items:
        - httpd
        - chronyd
...

**Comment by deepaklor** [comment]
$ ansible dev -m shell -a "systemctl status chronyd -l && systemctl status httpd -l"

**Comment by deepaklor** [comment]
# How to check all necessary services are active using adhoc command,

why -o in adhoc command?

$ ansible dev -m shell -a "systemctl is-active chronyd"  -o | awk -F"|" '{print $1"-"$4}'

Output Example,
192.168.56.3 - (stdout) active

$ ansible dev -m shell -a "systemctl is-active chronyd"  -o | awk -F"|" '{print $1"-"$4}'

Output Example,
192.168.56.3 - (stdout) active

**Comment by deepaklor** [comment]
# How to check disk space for specific servers using Ansible Adhoc command.

$ ansible dev -m shell -a "df -hT -x tmpfs"

**Comment by deepaklor** [comment]
# How to check RAM for any servers,

$ ansible dev -m shell -a "free -m"

**Comment by deepaklor** [comment]
ADHOC command the simplest,

$ ansible dev -a "uptime"

**Comment by deepaklor** [comment]
# The same above adhoc command with the module included, there is no difference between the commands as default module is command there fore omitting is also fine when using ansible adhoc command.

$ ansible dev -m command -a "uptime"

**Comment by deepaklor** [comment]
# How to check the logs of the server and especially when you have many servers, example 100 application servers you need to check logs to ensure all are working as expected,

$ ansible dev -m shell -a "tail -n 10 /var/log/messages"

**Comment by Shaps** [comment]
Hi @deepaklor,

Thanks for submitting this, I'm not sure what all those comments are, can you please re-open a new issue and just post what the suggestion is about, there's no need to paste all the stdout. If you have multiple suggestions, please open multiple issues.
As a reference, you can have a look at #16 which is how the suggestion should look like.
