### ISSUE TITLE
How to make Systems Administrator life easy using Ansible

### ISSUE THREAD

**Issue by deepaklor** [ansible-community/ansible-london-meetup#18]
## Talk title

How to Make Systems Administrator life easy using Ansible?

## Talk Description

How to use Ansible for day to day challenges and save time for the System Administrators.
Description and ways to use the  Ansible ADHOC commands.
How to write simple playbooks and Orchestrate the business requirements.

## Estimated Duration
30 minutes

## Twitter Handle
deepaklor

**Comment by Shaps** [comment]
Hi @deepaklor, 

thank you very much for taking the time to re-create this!

**Comment by gundalow** [comment]
Hi,
The next meetup is Tuesday 19th March https://www.meetup.com/Ansible-London/events/258726000/
Does this date work for you? If not we will have another meetup a few months after.

**Comment by gundalow** [comment]
The  [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) is now fully scheduled, expect the one after to be in ~August.

**Comment by phips** [comment]
Hello @deepaklor – did you still want to give this talk? It would be a brilliant one to do, and we've got three slots free for the upcoming [August 29th meetup](https://www.meetup.com/Ansible-London/events/263354480/).

**Comment by deepaklor** [comment]
yes should be possible and i confirm the schedule.

**Comment by phips** [comment]
Great, thanks! If you can tune the talk to be around 20 minutes please that would be fab Drop me an email to `markp AT redhat.com` when you're able to confirm attendance and I'll put all the details on the meetup page 👍🏻

**Comment by deepaklor** [comment]
Sure, will do. i will confirm the attendance.

**Comment by phips** [comment]
Hello @deepaklor – are you able to make August 29th? No worries if not, just let us know please so we can confirm the last speaking slot. Many thanks!

**Comment by deepaklor** [comment]
I already confirmed.

**Comment by phips** [comment]
> I already confirmed.
> […](#)

Ah, thanks – I haven't seen an email, did you email me? If not, please do – with your full name, talk title and brief synopsis please. I'll get all the details on the meetup.com page then 👍 Thank you!

**Comment by deepaklor** [comment]
Apologies for the delay, I will be confirming all the details asap today
and send it tonight

**Comment by deepaklor** [comment]
Hi ,

Please find the details below and let me know if you need any other details
to confirm.

FULL NAME: DEEPAK KUMAR RAMANUJAM
https://uk.linkedin.com/in/deepak-kumar-ramanujam-28326543

TALK TITLE:

How to make Systems Administrator life easy using Ansible


BRIEF SYNOPSIS:

How to use Ansible for day to day challenges and save time for the System
Administrators.
Description and ways to use the Ansible ADHOC commands.
How to write simple playbooks and Orchestrate the business requirements.
https://github.com/ansible-community/ansible-london-meetup/issues/18

**Comment by gundalow** [comment]
Hi, thanks again for your talk.

When you get a chance could you please raise a PR to add your slides to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-08-29 and update `README.rst`
