### ISSUE TITLE
Jinja2 filters

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#2]
## Talk title
Jinja2 filters

## Talk Description
Describe how to create Jinja2 filters and how to distribute and use them via an Ansible role.

## Estimated Duration
20-30 minutes

**Comment by gundalow** [comment]
Selected for October 2018 https://www.meetup.com/Ansible-London/events/254403376/

**Comment by Shaps** [comment]
Thanks @jtyr for this and the bonus presentation, info added here: https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2018-10-15

**Comment by jtyr** [comment]
Slides available here:
https://www.slideshare.net/jtyr/jinja-2-filters/
