### ISSUE TITLE
Variable precedence: Where should I put a variable?

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#23]
## Talk title
Variable precedence: Where should I put a variable?

## Talk Description
This talk will show where everywhere we can define variables in Ansible and how they override each other.

## Estimated Duration
30 mins

## Twitter Handle
@JiriTyr

**Comment by gundalow** [comment]
19th March good for you?

**Comment by jtyr** [comment]
Yes

**Comment by gundalow** [comment]
Hi
Looking forward to your presentation tomorrow. When you arrive (around 6pm) please come and find me so we can get you setup with a microphone.

If you haven't connected to Sainsbury's WiFi before I suggest you do that from reception (ground floor) as you need an SMS code as the auditorium is in the basement and you may not have mobile reception.

**Comment by gundalow** [comment]
@jtyr Thank you as always for your presentation. Could you please let me know once it's uploaded to https://www.slideshare.net/jtyr/ and I'll link to it from https://github.com/ansible-community/ansible-london-meetup/blob/master/presentations/

**Comment by jtyr** [comment]
@gundalow Thanks for organizing the meetup. Here are the slides: https://www.slideshare.net/jtyr/variable-precedence-where-should-i-put-a-variable

**Comment by gundalow** [comment]
Talk for next time? Please create an issue
