### ISSUE TITLE
How I Provision My Macbook with Ansible

### ISSUE THREAD

**Issue by adamchainz** [ansible-community/ansible-london-meetup#25]
## Talk title

How I Provision My Macbook with Ansible

## Talk Description

For nearly 5 years I've been installing software and setting up dotfiles on my Macbook with Ansible. It has saved me a bunch of time - first in synchronizing between home and work laptops, and second when they have to get wiped! I'll walk through how it works and hopefully inspire the audience to use Ansible for automating their personal IT too 😎

[ The repo containing my playbook: https://github.com/adamchainz/mac-ansible ]

## Estimated Duration

10-15 minutes, depends on how long the slot is :)

## Twitter Handle

@adamchainz

## Sponsorship

Not right now I'm afraid..

**Comment by gundalow** [comment]
@adamchainz Thanks for the offer of the talk. Looks like we could fit you in on Tuesday 19th March Meetup https://www.meetup.com/Ansible-London/events/258726000/ would that work for you?

**Comment by adamchainz** [comment]
Yes, I'll be there!

**Comment by gundalow** [comment]
Excellent, I've added you to https://www.meetup.com/Ansible-London/events/258726000/
and done a tweet.

**Comment by gundalow** [comment]
This presentation feels like a great opertunity to mention https://github.com/ansible/community/wiki/macos

**Comment by adamchainz** [comment]
Perfect, will mention!

**Comment by gundalow** [comment]
Hi
Looking forward to your presentation tomorrow. When you arrive (around 6pm) please come and find me so we can get you setup with a microphone.

If you haven't connected to Sainsbury's WiFi before I suggest you do that from reception (ground floor) as you need an SMS code as the auditorium is in the basement and you may not have mobile reception.

**Comment by adamchainz** [comment]
I'll see you there! Thanks for the WiFi hint.

**Comment by gundalow** [comment]
Presentations added to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-03-19

If you do a blog post feel free to add a link in here.
Also feel free to link to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-03-19 from https://github.com/adamchainz/mac-ansible (or else where)

Thank you again for a great talk!
