### ISSUE TITLE
Using pre-commit to ease linting Ansible code repos

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-london-meetup#29]
## Talk title
Linting Ansible

## Talk Description
How to introduce linting gradually on old code repositories and ease its maintenance. 

While it touches ansible-lint is not limited to it and it covers use of multiple linters via pre-commit.

## Estimated Duration
30min

## Twitter Handle
sbarnea

**Comment by gundalow** [comment]
Hi,
I've just scheduled our next meetup on [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) would you be available to present then?

**Comment by gundalow** [comment]
Hi,
I've just scheduled our next meetup on [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) would you be available to present then?

**Comment by gundalow** [comment]
The  [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) is now fully scheduled, expect the one after to be in ~August.

**Comment by ssbarnea** [comment]
@gundalow yep. Btw, check to see if you can use Milestone or Projects to mark the scheduled ones. It would make much easier to identify when each proposal is going to happen.

**Comment by gundalow** [comment]
Nice idea, that might help us if we have two Meetups scheduled at once.

**Comment by Shaps** [comment]
Hi @ssbarnea.  This could be a good talk for the next meetup ( Somewhere between end of Feb and mid Mar ), we usually try to keep the talks to a mid-level of complexity as not everyone in the meetup may be familiar with Ansible. Do you think the presentation could be done in 20 min?

Thanks!

**Comment by ssbarnea** [comment]
@ssbarnea Yes, I can. I can do 20 min presentation (10-12m for slides, rest for questions) on how to enable linting. Only requirements I need is to know: basic git and what a playbook or role is. I will keep the advanced stuff out, probably I will also have a longer blog post addressing more advanced stuff, in case anyone asks about these.

**Comment by Shaps** [comment]
@ssbarnea Next meetup will be on March 11th. Do you think you can make it?

**Comment by ssbarnea** [comment]
@Shaps Yes, I can. Added to my calendar, reminder, going for tickets now.

**Comment by Shaps** [comment]
Hi @ssbarnea,
We are trying to organize this to be an online event, would you be available to speak in the next 2-4 weeks?

**Comment by ssbarnea** [comment]
@Shaps yes I will.

**Comment by Shaps** [comment]
@ssbarnea Cool! The meetup date will be Jun 3rd, hopefully that works for you!

**Comment by phips** [comment]
Hello @ssbarnea! Can you drop me an email to `markp at redhat dot com` please? I need to bring you and the other speaker into an email conversation with the hosts. Need a quick run through of the Remo platform on the 1st if you're able 👍 Thanks!

**Comment by gundalow** [comment]
@ssbarnea Thank you again for your presentation. Do you have a link to the slides you could add to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2020-06-03

**Comment by ssbarnea** [comment]
Yep, all presentations are hosted at https://sbarnea.com/slides/#/
