### ISSUE TITLE
The way of managing Ansible roles across different environments

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#3]
## Talk title
The way of managing Ansible roles across different environments

## Talk Description
Demonstrate how to manage Ansible roles across multiple environments (dev, qa, stage, prod) . How to version it, how to make sure each environment is using only specific version of the roles and how to push versions across all the environments in the meaner of continuous delivery.

## Estimated Duration
20-30 mins

**Comment by Shaps** [comment]
:+1:

**Comment by gundalow** [comment]
@jtyr I've updated the issue to use the new template, could you please edit the issue to include estimated duration. Thanks in advance!

**Comment by manjeetchauhan211** [comment]
Are we going to include this on 16th October london presentation, please confirm thanks

**Comment by Shaps** [comment]
@manjeetchauhan211 No, this won't be in the Oct 15th meetup.

**Comment by gundalow** [comment]
@jtyr  would you be available to present at the December meetup https://www.meetup.com/Ansible-London/events/254878934/

**Comment by jtyr** [comment]
Yes.

**Comment by gundalow** [comment]
@jtyr Could you please use a dark theme for your slides. The recording are a bit washed out.

Hopefully we can capture the video direct from your laptop, though we will see

**Comment by jtyr** [comment]
I thought they split the HDMI signal and record it in the say quality what's projected on the big screen.

**Comment by gundalow** [comment]
Hopefully we can do this via BlueJean screen sharing, though there were some technical issues last time. The backup is the video camera that the venue provide

**Comment by gundalow** [comment]
@jtyr Looking forward to seeing you on Wednesday 12th December!

**Comment by gundalow** [comment]
@jtyr Thank you, as always for your presentations! It's been added to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2018-12-12

Over the next week or so I'll get the video processed and linked to the above URL.
