### ISSUE TITLE
Ansible to harden Linux OS @FT

### ISSUE THREAD

**Issue by nayanashettyft** [ansible-community/ansible-london-meetup#30]
## Talk Description
FT had been mainly using RHEL 6 until 2017. The way we hardened them to be inline with our Operating system standards was by creating RPMs for each component example  RPMs for LDAP, SUDO, LOGGING, etc. In 2017 when we had more and more teams started moving to use Amazon Linux, we decided to not use RPMs to harden our severs but instead create Ansible modules. We bundle these into an ansible-playbook that can be pulled from a central location and it runs on servers at regular intervals. So an engineer in the FT who wants to build a Amazon Linux server would get the latest/any ami from Amazon and then runs the ansible playbook as part of the User Data while building the server. In this talk I would like to go into the details of how these modules work, what kind of testing we do, the pipeline we have when we want to make a new release and the benefits we have been seeing due to this approach to harden servers.
## Twitter Handle

@ShettyNy

**Comment by gundalow** [comment]
@nayanashettyft Thank you for the topic, this sound very interesting.
We are just working out the date for the next meetup, most likely early June. I'll update once this is confirmed.

**Comment by gundalow** [comment]
Hi,
I've just scheduled our next meetup on [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) would you be available to present then?

Depending on the other talks, and you availability, we'll pick on of this or #31

**Comment by nayanashettyft** [comment]
Hi,
I am available and willing to do a talk. I am happy to do either of them. Let me know when which one we want to do for this time.

**Comment by gundalow** [comment]
We will go with #31 for June
I expect the one after to be in ~August.

**Comment by phips** [comment]
Hello @nayanashettyft - would you be available, and willing, again, to speak at the scheduled meetup on November 25th? Many thanks!

**Comment by nayanashettyft** [comment]
I would like to do 1 again but I am on holiday on 25th November. I can do it early next year.

**Comment by phips** [comment]
Thanks for the quick reply. No worries, will come back to you in the new year. Thanks!

**Comment by Shaps** [comment]
Hi @nayanashettyft! We have scheduled our next meetup for the Jan 29th, would you be available to speak? Thanks!

**Comment by gundalow** [comment]
@nayanashettyft Hi, the next Virtual London Ansible Meetup will be on Thursday 10th September.

Would you be interested in presenting remotely at this?

**Comment by nayanashettyft** [comment]
Hi @gundalow, 

We have just gone through making our ansible OS hardening scripts that worked with Amazon Linux 1 to now work with Amazon Linux2. We do have a good story around how ansible is used for hardening and how it helped us with the  moving to AL2. Either me or someone in my team could do a talk about this. September might be too early for us to prepare and have the presentation ready give it is holiday season, but will conform this with you early next week if that is ok with you.

Thanks

**Comment by gundalow** [comment]
@nayanashettyft Sure, let us know.
After September, we should have something in October/November it would be great to have you back on the (virtual) stage.

**Comment by nayanashettyft** [comment]
Hi @gundalow, I would like to do this talk in November if that is ok please.
It has been a while since I made it to the meetup, virtual one in September looks very interesting and I find it easy to attend because it is virtual :)

**Comment by nayanashettyft** [comment]
Hi @gundalow, @alex20484096 from my team has agreed to do this talk. Alex lead the efforts in porting the ansible scripts to work with Amazon Linux2 OS recently and I think would be the best person to do the talk.

**Comment by gundalow** [comment]
@alex20484096 We've scheduled the next (virtual) London Meetup for Tuesday 25th of May.
Would you be available to give your talk then?

**Comment by gundalow** [comment]
@nayanashettyft Hi, would anyone in your team be interested in giving this talk for the next (virtual) London Meetup on Tuesday 25th of May?

**Comment by nayanashettyft** [comment]
Hi @gundalow I think Alex is on leave until the end of this week, I can check with him early next week and get back to you on this

**Comment by alex20484096** [comment]
Hi @gundalow I am available on the 25th of May and I am very happy to do it

**Comment by gundalow** [comment]
> Hi @gundalow I am available on the 25th of May and I am very happy to do it

@alex20484096 that's great. Is 20 minutes still OK?

**Comment by alex20484096** [comment]
@gundalow 20 minutes is fine!

**Comment by gundalow** [comment]
@alex20484096 Thank you.
Event created here: https://www.meetup.com/Ansible-London/events/278093392/
1. Could you please email me gundalow at redhat dot com
2. Please share the link
3. If you'd like me to publicise this using your (and or FT's) Twitter please add a comment here with those Twitter account names.

Thanks again

**Comment by gundalow** [comment]
@alex20484096 Thank you once again for your great talk, and thank you @nayanashettyft for suggesting it.

@alex20484096 When you get a chance could you please
1. Raise a PR (Pull Request) to add your slides (PDF or link to external site) into https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2021-05-25
2. Update the README.md to point to the slides (just the filename is fine)
3. Add any links you think people may find useful into the README.md
4. Send me an email with your postal address and t-shirt size.

**Comment by alex20484096** [comment]
@gundalow  Thank you for having me, it was a great experience! 
Sure! I will do that!

**Comment by gundalow** [comment]
@nayanashettyft @alex20484096 Hi, I was just reviewing older issues, and doesn't look like we got a copy of the slides. 

I know this was a while ago, so no problem if you don't have the slides anymore.

If you do, please could you upload them:
1. Raise a PR (Pull Request) to add your slides (PDF or link to external site) into https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2021-05-25
2. Update the README.md to point to the slides (just the filename is fine)
3. Add any links you think people may find useful into the README.md

Thanks
