### ISSUE TITLE
Our learnings since we started using Ansible

### ISSUE THREAD

**Issue by nayanashettyft** [ansible-community/ansible-london-meetup#31]
## Talk Description
We started using ansible actively in my team toward the end of 2017 beginning of 2018. This was green field for us and very quickly we ramped up to having most of our production central monitoring systems using Ansible now. We are now answering questions on what is our standards around creating new ansible modules and playbooks, how do we test in a sensible and sustainable way. It would be interesting to share our story and what we would do differently if we started over this again.

## Estimated Duration
10-15mins

## Twitter Handle

@ShettyNy

**Comment by gundalow** [comment]
Hi,
I've just scheduled our next meetup on [Thursday 13th June](https://www.meetup.com/Ansible-London/events/260638878/) would you be available to present then?

**Comment by gundalow** [comment]
Excellent, let's do this one `Our learnings since we started using Ansible` in June.

**Comment by nayanashettyft** [comment]
Sure, will share the slide here when I am done with them

**Comment by nayanashettyft** [comment]
Hi @gundalow, I have been timing my talk and I think it will take me 20-25mins. Do you think that will be ok or should I work on cutting short my talk?

**Comment by Shaps** [comment]
Hi @nayanashettyft, Thanks for your talk at the meetup! We have now added the meetup directory [here](https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-06-13). If you want to share your slides, please raise a PR!
