### ISSUE TITLE
How does Ansible's agentless architecture work?

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#32]
## Talk title
How does Ansible's agentless architecture work?

## Talk Description
This talk will discuss how Ansible packs and propagates its code to remote machine and how it runs it there.

## Estimated Duration
20 mins

## Twitter Handle
@JiriTyr

## Sponsorship
N/A

**Comment by gundalow** [comment]
Thanks, scheduled

**Comment by jtyr** [comment]
Slides published here:
https://www.slideshare.net/jtyr/how-does-ansibles-agentless-architecture-work

**Comment by Shaps** [comment]
@jtyr Thanks for the slides, and for the talk!
