### ISSUE TITLE
ansible-lint future and its fixing new feature

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-london-meetup#33]
## Talk title

Ansible-lint future and its fixing new feature.

## Talk Description

Introduction to the uplifted status of ansible-lint, its recent changes and the auto-fixing feature.

## Estimated Duration
30min

## Twitter Handle
sbarnea

## Sponsorship
Nope.

**Comment by gundalow** [comment]
Scheduled for Tuesday 19th April

**Comment by ssbarnea** [comment]
I might replace that talk with one about ansible-lint v6, its future and the new experimental auto-fixing feature.

**Comment by gundalow** [comment]
Thanks for the presentation.
Slides can be found at https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2022-04-19
