### ISSUE TITLE
33% higher profit; 300% more innovation; 125% less burnout - Positive Psychology with Ansible

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible-community/ansible-london-meetup#34]
## Talk title
33% higher profit; 300% more innovation; 125% less burnout - Positive Psychology with Ansible

## Talk Description
This proposal has been submitted for AnsibleFest in Atlanta 2019 - I'd also like to see if there's an appetite for it in London, looking at the non-technical benefits of Ansible to organizations:

Practising Positive Psychology in the workplace has been shown to bring numerous quantifiable benefits to organisations - the Harvard Business Review found a 125% reduction in burnout rate of staff, and a 300% increase in innovation. Forbes a 66% decrease in sick leave. A study by Gallup uncovered a 51% decrease in staff turnover, and even 33% higher profitability.

Effective implementation of Ansible and Ansible Tower not only brings the benefits of automation to organisations - it actively supports the introduction and on-going practise of Positive Psychology (as studied and championed by Martin Seligman) in the workplace. In this presentation we will explore the link between these two seemingly disparate areas, and set out a route for Ansible to bring these benefits to your organisation. 

Imagine being on track to increase profitability, engagement and morale through the implementation of one single Open Source software tool.

## Estimated Duration
30-40mins but can be adjusted to suit

## Twitter Handle

jamesfreeman959

## Sponsorship

Not this time but can we discuss suggested sponsorship amounts?

**Comment by gundalow** [comment]
Hi James, 
Thanks for the talk, sounds really good. We've already got a full agenda for June, so will save this for the next one, date TBA.

I'll drop you an email regarding sponsorship.

**Comment by gundalow** [comment]
Hi, thanks again for your talk.

When you get a chance could you please raise a PR to add your slides to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-08-29 and update `README.rst`
