### ISSUE TITLE
Talks people have requested – can you help?

### ISSUE THREAD

**Issue by phips** [ansible-community/ansible-london-meetup#37]
At the June meetup we asked people what talks they'd like to hear at a future meetup. Here's a list of topics – if you'd like to speak on anything along these lines [please submit your talk here](https://github.com/ansible-community/ansible-london-meetup/issues/new/choose)!

# Beginner topics
- Writing playbooks
- Role development do's & don'ts

# Infrastructure related
- More infrastructure-as-code
- Building infrastructure from scratch with Ansible
- ~~Testing of Ansible roles~~ [Done](https://github.com/ansible-community/ansible-london-meetup/issues/41)
- Migrating content across Ansible versions; techniques to identify what playbooks/roles need attention and by when

# Scaling
- Large scale deployment pipelines & processes to help Ansible across large teams

# Developing for Ansible
- Examples for new people to contribute to the Ansible project
- Developing Ansible modules
- Anything presented by an Ansible core developer

# GUI
- Tower/AWX best practices
- [Ansible Tower use cases](https://github.com/ansible-community/ansible-london-meetup/issues/55) (planned for meet no.2 2020)

# Third party tools
- ~~VMware ESXi automation with Ansible, persistent storage solutions under ESXi~~ [Done](https://github.com/ansible-community/ansible-london-meetup/issues/38)
- Infoblox as dynamic inventory

# Microsoft related
- Ansible and Powershell
- More on Windows admin

**Comment by ssbarnea** [comment]
If anyone wants I can make a presentation on how to test Ansible roles or playbooks with Molecule.

**Comment by Shaps** [comment]
@ssbarnea Can you create an issue for it? We have a full schedule for the Jan meetup, but we can add you to the next one!

**Comment by mikeycmccarthy** [comment]
I added a proposal talk about how we provide a multi tenant ansible tower for developers to deploy their apps from if that's of interest. Mistakes made, things learnt, some.of the tower features we use...that kind of thing.

**Comment by phips** [comment]
We’d love to have you talk Mike! Next meetup is now fully booked, but can we provisionally grab you for the next one? No dates set yet, but we’re trying to maintain a cadence of 6-8 weeks, so possibly around end of March?

**Comment by mikeycmccarthy** [comment]
Sounds good to me!

**Comment by ssbarnea** [comment]
@Shaps 
I can do presentations about [Using molecule to test Ansible core](https://github.com/ansible-community/ansible-london-meetup/issues/33) and [Linting Ansible code](https://github.com/ansible-community/ansible-london-meetup/issues/29) -- please comment on them and also mention how advanced they should be or which answers you want me to address.
