### ISSUE TITLE
Provisioning VMs on VMware ESXi with Ansible

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#38]
## Talk title
Provisioning VMs on VMware ESXi with Ansible

## Talk Description
This presentation will show how to use Ansible to build VM templates, how to upload them to vCenter and how to build and rebuild VMs from such template.

## Estimated Duration
30min

## Notes
- This talk addresses one of the topics (`VMware ESXi automation with Ansible`) from issue #37.
- I will walk through a [role](https://github.com/jtyr/ansible-vmware_vm_provisioning) which I have developed some time ago.

## Twitter Handle
@JiriTyr

**Comment by phips** [comment]
Brilliant Jiri, thanks! The August meetup is looking organised now, so let's keep this one for the following meetup.

**Comment by phips** [comment]
Hey @jtyr! We've regrettably had a drop out from the meetup – and it was going to feature some VMware. Would you like to give this talk on August 29th now? Many thanks for stepping in if you can!

**Comment by jtyr** [comment]
Yes, I can present it on August 29th.

**Comment by phips** [comment]
Magic, thanks @jtyr !

**Comment by phips** [comment]
Morning @jtyr! Would it be terribly rude of me to ask if you could do this on the _next_ meetup after this one in August please? The 'drop out' I thought we had wasn't – they were just slow to respond. They're a new speaker, so it would be great to give them this opportunity. Would you mind sitting this one out please? As ever, many thanks for your continuing contributions to the meetup!

**Comment by jtyr** [comment]
No problem. Let's do it next time.

**Comment by phips** [comment]
Fab, thank you Jiri!

**Comment by jtyr** [comment]
@phips I have updated the talk description to cover a little bit more topics. Please feel consider this talk for the next meetup (25th Nov).

**Comment by phips** [comment]
Thanks Jiri! That’s perfect.  I was just about to ping you and see if you were available to do this on the 25th - consider yourself booked. And, as ever, thanks so much for your keen volunteering!

**Comment by gundalow** [comment]
Just to point out the [November 25th](https://www.meetup.com/Ansible-London/events/265681961/) event is at KPMG in Canary Wharf

**Comment by jtyr** [comment]
I have noticed. The location is fine for me as long as they gonna have some :beer: there ;o)

**Comment by gundalow** [comment]
@jtyr  Thank you again for your presentation. When you get a chance could you please raise a PR to add your slides into https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-11-25 Thanks.
