### ISSUE TITLE
The Ansible way of Administration

### ISSUE THREAD

**Issue by vvvinodkumar** [ansible-community/ansible-london-meetup#40]
## Talk title
The Ansible way of Administration

## Talk Description
How quick is ansible in the day to day adminstration. How it helps the administrator in performing his day to day tasks, perform the activities quickly and efficiently in a robust manner.

## Estimated Duration
10-15mins

## Twitter Handle

https://twitter.com/vvvinodkumar

## Sponsorship
no

**Comment by gundalow** [comment]
@vvvinodkumar Thank you for your topic.

The next Virtual London Ansible Meetup will be on Thursday 10th September.

Would you be interested in presenting remotely at this?

**Comment by gundalow** [comment]
@vvvinodkumar Would you be interested in presenting next week on Thursday 10th September?

**Comment by gundalow** [comment]
@vvvinodkumar We've scheduled the next (virtual) London Meetup for Tuesday 25th of May.
Would you be available to give your talk then?

**Comment by gundalow** [comment]
@vvvinodkumar Are you interested in presenting at the next virtual London Meetup on Wednesday 18th May?
