### ISSUE TITLE
Continious testing of ansible roles with docker

### ISSUE THREAD

**Issue by vladimirtiukhtin** [ansible-community/ansible-london-meetup#41]
## Talk title
Continious testing of ansible roles with docker

## Talk Description
- Why do we need continious testing
- Why docker
- Is systemd a problem
- Integrating all together

## Estimated Duration
15 min

## Twitter Handle
Don't use twitter

## Sponsorship
Yes. We can fully host an upcoming meetup

**Comment by phips** [comment]
Booked for November 25th 👍🏻

**Comment by gundalow** [comment]
@vladimirtiukhtin Thank you again for your presentation, and for hosting and sponsoring the event, everybody spoke very positively about the venue. When you get a chance could you please raise a PR to add your slides into https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-11-25 Thanks.
