### ISSUE TITLE
Managing Production Vault Clusters with Ansible

### ISSUE THREAD

**Issue by devops-rob** [ansible-community/ansible-london-meetup#42]
## Talk title
Managing Production Vault Clusters with Ansible

## Talk Description
When deploying and managing enterprise grade production vault clusters, there are many elements of platform configuration which need to be managed in a controlled way.  This talk will explore the workflows to achieve this and the vital role that Ansible plays in the success of managing such a platform.

## Estimated Duration
20-25 minutes

## Twitter Handle
@devops_rob

## Sponsorship
No

**Comment by phips** [comment]
Great, thanks Rob! Nice to meet you last night too.

**Comment by phips** [comment]
Hello @devops-rob – do you think you could do this talk on November 25th? Let us know if that works for you. Many thanks!

**Comment by gundalow** [comment]
Just to point out the [November 25th](https://www.meetup.com/Ansible-London/events/265681961/) event is at KPMG in Canary Wharf

**Comment by devops-rob** [comment]
Hey Folks, 

Unfortunately I am out of the country from November 15th until November 29th so will not be able to attend this event.  I'm happy to give the talk at the next one after November.

Thanks

**Comment by phips** [comment]
No worries. Thanks for confirming so quickly Rob.

**Comment by Shaps** [comment]
Hi @devops-rob next Meetup is scheduled for [January 29th](https://www.meetup.com/Ansible-London/events/267275106/) at G-Research. Would you be available for this?
Thanks!

**Comment by devops-rob** [comment]
Hi @Shaps 
Sure I can do that.  G-Research are actually my current client so that works out nicely as I will already be on site.  Will this be recorded?

**Comment by Shaps** [comment]
Hi @devops-rob, unfortunately we now have a full schedule for the Jan Meetup, but it would be great if you could do this at the next meetup. We usually try to keep a 6-8 weeks cadence, so you can expect the next one to be around end of February and mid March

**Comment by devops-rob** [comment]
Ahh I'm travelling between those dates. I have two trips in that period so the earlier you can confirm a date the better.

**Comment by Shaps** [comment]
@devops-rob i think it’s more likely going to be around mid/end March, would you be available for that? We’ll schedule it for the one after that if not

**Comment by devops-rob** [comment]
@Shaps I'm in Vegas from 19th March for 6 days and in Amsterdam for 5 days from 29th March so likely I will be unavailable depending on the exact date.

**Comment by phips** [comment]
We have no dates as yet Rob. If you’d like to speak, we’d definitely like you to :) so we can aim for dates when you _can_ make it. More than happy to check with you when we start arranging it.

**Comment by devops-rob** [comment]
Yes please @phips that would be great

**Comment by Shaps** [comment]
Hi @devops-rob,
We now have the date for the next meetup, It's going to be on March 11th. Do you think you can make it?

**Comment by devops-rob** [comment]
Sure @Shaps I can make 11th March

**Comment by devops-rob** [comment]
Hi @Shaps can I go first on the night with my talk please? I have far to travel so would like to leave early to catch my train.

**Comment by phips** [comment]
Not a problem Rob 👍

**Comment by Shaps** [comment]
Hi @devops-rob, 
unfortunately, as you may have seen in the meetup announcement, we've come to the decision of cancelling this meetup. We'll be letting you know the new date once we have it!

**Comment by devops-rob** [comment]
No worries @Shaps. Keep me posted on new dates

**Comment by Shaps** [comment]
Hi @devops-rob ,
We are trying to organize this to be an online event, would you be available to speak in the next 2-4 weeks?

**Comment by devops-rob** [comment]
Hi @Shaps I've just moved house so it's pretty hectic here at the moment.  Probably won't be settled in enough to do the talk until the next 4-6 weeks.

**Comment by Shaps** [comment]
@devops-rob, no worries, we'll leave this open and schedule it for the meetup after next!

**Comment by gundalow** [comment]
@devops-rob  I hope you are all settled in your new home.

The next Virtual London Ansible Meetup will be on Thursday 10th September.

Would you be interested in presenting remotely at this?

**Comment by devops-rob** [comment]
Sure thing. Count me in!

**Comment by gundalow** [comment]
@devops-rob excellent
1) Is 20-25 minutes still good for you?
2) could you please drop me an email to gundalow at redhat.com so I can send you an presenters link.

**Comment by devops-rob** [comment]
Yes that length is all good and I'll drop you an email. Cheers

**Comment by gundalow** [comment]
@devops-rob Thank you once again for a great talk. When you get a chance could you possible update the README and add your slides to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2020-09-10

**Comment by devops-rob** [comment]
Sure thing @gundalow sorry, I only just saw this.  Will do this now.  I guess I just need to create a folk and do a PR?

**Comment by devops-rob** [comment]
created a PR here: https://github.com/ansible-community/ansible-london-meetup/pull/67

**Comment by gundalow** [comment]
Thanks, could you please update https://github.com/ansible-community/ansible-london-meetup/blob/master/presentations/2020-09-10/README.md as well.
