### ISSUE TITLE
Model-Driven Network Management with Ansible

### ISSUE THREAD

**Issue by jgcumming** [ansible-community/ansible-london-meetup#47]
## Talk title
Model-Driven Network Management with Ansible

## Talk Description
This presentation (and associated live demos - perhaps!) will cover what Model-Driven Network Management is and how Ansible can be used to manage configuration elements of global network operators.

## Estimated Duration
1h (or less depending on the available timeslot and what content I include :-) )

## Twitter Handle
@nokia_jcumming

**Comment by gundalow** [comment]
Hi,
Thank you for your talk suggestion, I'm sure people will find it interesting. 

Talkwise, we generally limit to 20-30 minutes. This allows us to have a range of different topics covered at each meetup.

**Comment by phips** [comment]
Hello @jgcumming! What are your thoughts on giving the talk, in whatever form it takes, in a 20 minute session? We tend to find this is the optimum time to capture people's imagination (and importantly, hold it ;-)) You don't have to tell them everything, give the audience enough to understand and want to go learn more. If you can cut the talk down a bit, we've a session coming up in late January. It would be ace to book you for it! Cheers

**Comment by jgcumming** [comment]
Hi Mark,

What are the dates you are planning for?

James

**Comment by phips** [comment]
Hello James. It'll be January 29th. Meetup page will be up this week.

**Comment by Shaps** [comment]
@jgcumming ^

**Comment by jgcumming** [comment]
I can make it on 29th.  I'll prepare an abstract shortly.

**Comment by Shaps** [comment]
@jgcumming Nice! I'll set this as scheduled then.

Thanks!

**Comment by phips** [comment]
> I can make it on 29th. I'll prepare an abstract shortly.

Hello @jgcumming — would you have a title for us please? Would be good to get the meetup page updated. Just to check, you're OK with fitting it in to 20 minutes too? Thanks!

**Comment by phips** [comment]
You're on the meetup page James … 👏🏻 https://www.meetup.com/Ansible-London/events/267275106/

**Comment by jgcumming** [comment]
Thanks Mark.  The title is good.

**Comment by Shaps** [comment]
Hi @jgcumming!
Thanks a lot for your talk, do you think you can put the slides in the repo? If you don't have time, feel free to email them over to me and I'll put them online ( That is, if you're ok with them being online ).

Thanks!

**Comment by gundalow** [comment]
@jgcumming Hi, do you have a copy of the slides you could upload to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2020-01-29
