### ISSUE TITLE
Ansible Inventory Plugin

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#48]
## Talk title
How to create an Inventory Plugin

## Talk Description
In one of the past meetups, we have learned how to create a Dynamic Inventory Script. Ansible has evolved since and scripts were replaced by plugins. This talk will explore the differences between the Dynamic Inventory Script and the Inventory Plugin and will show how to write your own Inventory Plugin.

## Estimated Duration
30 mins

## Twitter Handle
@JiriTyr

## Sponsorship
N/A

**Comment by gundalow** [comment]
@jtyr The next Virtual London Ansible Meetup will be on Thursday 10th September. Would you be interested in presenting remotely at this?

**Comment by jtyr** [comment]
Hi @gundalow. I didn't touch Ansible for last 6 months (you know, cloud and containers) but I can certainly present this topic next week ;o)

**Comment by gundalow** [comment]
@jtyr Excellent. You will receive an email soon with details about Reno (the presentation platform)

**Comment by gundalow** [comment]
@jtyr once again than you for an excellent presentation.

Slides have been added, so I'll close this. 

Till next time!
