### ISSUE TITLE
How to create a Callback Plugin

### ISSUE THREAD

**Issue by jtyr** [ansible-community/ansible-london-meetup#49]
## Talk title
How to create a Callback Plugin

## Talk Description
Ansible is extensible via many kind of plugins. One of the kind is Callback Plugin which allows to customize the output displayed while running Ansible Playbook. This talk will show some of the existing Callback Plugins in action and also show how to write your own one.

## Estimated Duration
30 mins

## Twitter Handle
@JiriTyr

## Sponsorship
N/A

**Comment by Shaps** [comment]
Hi @jtyr! Next meetup is [January 29th](https://www.meetup.com/Ansible-London/events/267275106/), would you be available to do this talk?

Thanks!

**Comment by jtyr** [comment]
Yes, I can prepare the presentation for this meetup.

**Comment by Shaps** [comment]
@jtyr Fantastic!
Thanks

**Comment by Shaps** [comment]
Thanks for the talks and PR for adding the slides!
