### ISSUE TITLE
 Upgrading the backend database of a £3 billion business website on a Friday Afternoon with Ansible

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible-community/ansible-london-meetup#5]
## Talk title
 Upgrading the backend database of a £3 billion business website on a Friday Afternoon with Ansible

## Talk Description
I am giving the following talk at AnsibleFest in Austin in October and would be happy to repeat it in London at the MeetUp if there is interest: 

An unwritten rule in the world of IT Operations is that you never make changes on a Friday afternoon, especially not upgrading the backend database for a business e-commerce site contributing a £2 billion revenue. Ansible Tower makes the unthinkable thinkable by producing reliable, consistent, repeatable results, and removing the possibility of human error from activities. One major retailer of sportswear in the UK were so impressed with the performance of Ansible that they felt confident enough to do just this! 

## Estimated Duration
Can be tailored to suit - 15-30mins?

**Comment by Shaps** [comment]
This seems very interesting to me, and I think we should give it at least a 30 min slot, which I'm not sure we can accomodate for the Oct 15th meetup. Unless @gundalow says otherwise. 

@jamesfreeman959 would this be ok with you?

**Comment by gundalow** [comment]
Hi, I agree that this would be a great topic, though I don't think 15 minutes could give it justice and allow suitable time for Q&A.

We will have another meetup in December, date to be confirmed, so maybe we can pencil you in for December?

**Comment by gundalow** [comment]
@jamesfreeman959 would you be available to present at the December meetup https://www.meetup.com/Ansible-London/events/254878934/

**Comment by jamesfreeman959** [comment]
Yes absolutely - sorry for the late replies - for some reason I didn't get notification of these updates to my e-mail until yesterday evening. Anyway it would be a pleasure to come and present - thank you for the slot - I'll put it in the diary now. The talk went down well at AnsibleFest in Austin so hopefully in London it will be equally well received.

**Comment by gundalow** [comment]
@jamesfreeman959 Do you have a twitter handle, so I can `@mention` you?

**Comment by jamesfreeman959** [comment]
Yes indeed - please use @jamesfreeman959 - I haven't used it a lot but you're welcome to mention me. Might prompt me to start using it again!

**Comment by gundalow** [comment]
@jamesfreeman959 Looking forward to seeing you on Wednesday 12th December!

**Comment by jamesfreeman959** [comment]
@gundalow Likewise!

**Comment by gundalow** [comment]
@jamesfreeman959 Just realised we hadn't confirmed duration, is 30 minutes OK?

**Comment by jamesfreeman959** [comment]
Yes absolutely fine - I can always tailor it to suit anyway. Do you know roughly when you'll be putting me up to speak?

**Comment by jamesfreeman959** [comment]
Hi @gundalow - my son is poorly and on antibiotics - I'm still coming tonight but I'd like to avoid too late a bed time for him and I need to get back for him (it's a long story...). Is there any chance of a late alteration to the running order please? Could I possibly go on first or second? I wouldn't normally ask for a late change and I know the agenda has gone out, but I hope we might be able to agree an exception here.

**Comment by gundalow** [comment]
@jamesfreeman959 sorry to hear that, I totally understand.
6:00pm people arrive
6:30pm my intro
6:45pm your presentation

Does that work for you?

**Comment by jamesfreeman959** [comment]
Thank you so much @gundalow - that would be awesome. I'll hang around for as long as I am able but will discretely take my leave a little early. I'm more than happy to leave my contact details for attendees though so if I do miss out on any networking at the end, or there are follow on questions I'm very happy for those attending to contact me outside of the MeetUp. Perhaps I can leave some business cards just in case?

**Comment by gundalow** [comment]
Sure that would be great.

**Comment by gundalow** [comment]
@jamesfreeman959 Thank you once again for your presentation, it's been added to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2018-12-12

Over the next week or so I'll get the video processed and linked to the above URL.
