### ISSUE TITLE
Dennis McCarthy: The power of local facts

### ISSUE THREAD

**Issue by dmccuk** [ansible-community/ansible-london-meetup#50]
## Talk title
The power of local facts

## Talk Description
Cover how you can set up and use local server facts to act like an ENC (external node classifier) and provide fact variables to ansible to allow location, environment & role specific information to customise our ansible runs.

## Estimated Duration
20 minutes.

## Twitter Handle

@Lon_iac_meetup

## Sponsorship

I run the London infrastructure as code meetup and I ask the same questions of people who deliver talks for me. I'm not looking to buy the pizza or Drinks this time.

Thanks
Dennis

**Comment by dmccuk** [comment]
This is the code I'll use: https://github.com/dmccuk/ansible_local_facts
I'll update it quite a bit to include a few more use cases if you'd like me to do a talk.
Thanks
Dennis

**Comment by phips** [comment]
Hello @dmccuk – would you be available, and willing to give this talk on November 25th? That's the next meetup, which we're holding at KPMG in Canary Wharf. Let us know if that date works for you please? Thanks!

**Comment by dmccuk** [comment]
Hi Mark,

Yes I'm available. I'm already down to come to the meetup so its no problem
to do the talk.

Regards

Dennis

**Comment by phips** [comment]
Brilliant news Dennis, thank you! Considered yourself booked :)

**Comment by dmccuk** [comment]
Thanks, Mark,

I'll only need 20 minutes, possibly 25. Let me know what you need from me
nearer the time and I'll send it over.

Regards

Dennis

**Comment by phips** [comment]
20 minutes is perfect @dmccuk! I'll check what laptop connectivity we have at the venue, but you can probably safely assume HDMI is good. Just bring your stuff and we'll sort it 👍

**Comment by gundalow** [comment]
@dmccuk Thank you again for your presentation. When you get a chance could you please raise a PR to add your slides into https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2019-11-25 Thanks.

**Comment by dmccuk** [comment]
Thanks John,

Pull request raised. Any issues let me know.

Regards

Dennis
