### ISSUE TITLE
Verification and Validation Testing with GOSS and Ansible.

### ISSUE THREAD

**Issue by belfast77** [ansible-community/ansible-london-meetup#54]
## Talk title
Verification and Validation Testing with GOSS and Ansible.

## Talk Description
"One of the most important tests to run when deploying an IT solution is infrastructure verification and validation (V&V). In other words, making sure the system is configured the way it is supposed to be. Typically, V&V is one of the final phases of the test cycle and it is one of the most important. The goal of “V&V” is to make sure that it detects any inconsistencies between the system units that are integrated together or inconsistencies between deployment tiers such as Dev, Test, QA, Pre-Prod and Production. Obviously, this can be a major project, especially in organisations with lots of system components. Even for a small implementation it takes a lot of effort to make sure everything is working correctly. The risk of failure in this work is extremely high. To prevent this, requires a major effort leading up to go-live. The implementation team needs to verify all the details to make sure things are working properly. This adds up to a lot of effort to head off problems before the system goes live." *

The ability to automate the bulk of testing brings huge benefits in terms of time to complete and consistency of results.

GOSS stands for “GO Server Spec” and is an opensource tool and source code can be found at https://github.com/aelsabbahy/goss .

Many people develop their infrastructure as code, initially on Laptops with Vagrant and Virtulabox etc, then promote to an official dev environment which maybe in AWS , then a test environment which maybe on prem or different cloud platform or spec, then UIT, Pre-Pre-Prod and Prod, all may have variations or different teams managing them.

Differences can cause issues and therefore full V&V testing is really invaluable.

GOSS Is exceptionally easy to deploy an use, this presentation shows how you can use Ansible and GOSS together to verify and validate you deployments 

## Estimated Duration
15 Minutes

## Twitter Handle
https://twitter.com/TheKernelPanics

**Comment by gundalow** [comment]
@belfast77 Thank you for this, sounds great. We already have the talks lined up for the Jan Meetup, so maybe the one after that, once we've secured a date?

**Comment by belfast77** [comment]
@gundalow Yeah sure, no problem.

**Comment by gundalow** [comment]
@belfast77 Hope you are well

The next Virtual London Ansible Meetup will be on Thursday 10th September.

Would you be interested in presenting remotely at this?

**Comment by belfast77** [comment]
Hey @gundalow,

Hope you are well also mate.
Absolutely! I'm in!

Cheers
Colin

**Comment by gundalow** [comment]
@belfast77 Thank you once again for a great talk. When you get a chance could you possible update the README and add your slides to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2020-09-10

Once this lock down stuff is all over can't wait to have Dev Null and the kernel panics play at a meetup (summer BBQ?)

**Comment by gundalow** [comment]
Slides added in https://github.com/ansible-community/ansible-london-meetup/pull/66

Once again thanks for a great talk.
