### ISSUE TITLE
Running a multi-tenant Tower - The evolution of Ansible Tower at Gamesys

### ISSUE THREAD

**Issue by mikeycmccarthy** [ansible-community/ansible-london-meetup#55]
## Talk title
The Evolution of Ansible Tower at Gamesys

## Talk Description
We've been using Ansible Tower at Gamesys now for many years, and it has become the de facto standard for how we deploy our artefacts across environments. In this talk we'll share why we use Tower, what works well for us, and what we've learnt over the last few years that has led us to the setup we have now. And a quick peek at where we might go with it!

## Estimated Duration
1 hour

## Twitter Handle
@wallofmouths

## Sponsorship
Gamesys are always hiring!

**Comment by mikeycmccarthy** [comment]
We use virtualenvs, custom credentials, isolated instance groups etc so can cover real world usage of those

**Comment by Shaps** [comment]
@mikeycmccarthy I've seen your comment in #37. Can you just confirm you'll be available for the next meetup somewhere around mid-end March?
Thanks!

**Comment by mikeycmccarthy** [comment]
Hi, I can currently make most dates in March, just not the 12th.

**Comment by Shaps** [comment]
@mikeycmccarthy sounds good, we’ll try avoiding the 12th!

**Comment by Shaps** [comment]
Hi @mikeycmccarthy, 
The next meetup is going to be the 11th of March, can you let us know if you can make it?

**Comment by mikeycmccarthy** [comment]
Hey @Shaps , I can make that, looking forward to it.

**Comment by Shaps** [comment]
Hi @mikeycmccarthy , 
unfortunately, as you may have seen in the meetup announcement, we've come to the decision of cancelling this meetup. We'll be letting you know the new date once we have it!

**Comment by Shaps** [comment]
Hi @mikeycmccarthy, 
We are trying to organize this to be an online event, would you be available to speak in the next 2-4 weeks?

**Comment by mikeycmccarthy** [comment]
Good by me!

**Comment by Shaps** [comment]
Hi @mikeycmccarthy, We're going for June 3rd, hopefully that works for you!

**Comment by gundalow** [comment]
@mikeycmccarthy Thank you again for your presentation. Do you have a PDF of the slides you could upload to https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations/2020-06-03 (and update the link in `README.rst`)?
