### ISSUE TITLE
Integration tests in Ansible

### ISSUE THREAD

**Issue by pkleanthous-zz** [ansible-community/ansible-london-meetup#6]
## Talk title
Integration tests in Ansible

## Talk Description
How you can use molecule V2 to run integration tests  on AWS using Terraform and testinfra

**Comment by gundalow** [comment]
Thanks. How long would you estimate for this presentation?

**Comment by pkleanthous-zz** [comment]
Around 10-15 minutes

**Comment by gundalow** [comment]
@pkleanthous Would you be able to present on *Monday 15th October* at https://www.meetup.com/Ansible-London/events/254403376/

**Comment by pkleanthous-zz** [comment]
@gundalow Yeah can do.

**Comment by gundalow** [comment]
https://www.meetup.com/Ansible-London/events/254403376/ updated to include this as the 3rd talk

**Comment by gundalow** [comment]
Hi,
Just wondering if you saw the announcement that ansible-lint & Molecule are being adopted by Ansible https://groups.google.com/forum/#!topic/molecule-users/O1a_YNAjy-Q

Looking forward to your talk next week

**Comment by pkleanthous-zz** [comment]
Thanks for sharing the news. See you next Monday  :-)

**Comment by Shaps** [comment]
Hi @pkleanthous,
Thanks a lot for your presentation yesterday.
We have added a directory for the last meetup presentations [here]( https://github.com/ansible-community/ansible-london-meetup/tree/master/presentations). It would be great if you could add yours!

Thanks
