### ISSUE TITLE
Deploying PHP applications with Ansible, Ansible Vault and Ansistrano

### ISSUE THREAD

**Issue by opdavies** [ansible-community/ansible-london-meetup#60]
## Talk title

Deploying PHP applications with Ansible, Ansible Vault and Ansistrano

## Talk Description

Great! You’ve built your website, and now you just need to deploy it. There are various ways that this could be done - from (S)FTP, to SCP and rsync, to running commands like git pull and composer install directly on the server which is not ideal.

As well provisioning and maintaining your server configuration and running commands, you can also use Ansible to deploy your PHP application - leveraging relevant Ansible modules such as Git and Composer, custom Ansible roles, Ansible Vault for managing secrets, and features such as idempotency out of the box to build a simple deployment playbook.

We can then extend that and make it more robust by adding Ansistrano - a port of Capistrano - which adds extra features such as storing multiple builds for each project and the ability to roll-back if needed, customising your build steps using built-in hooks, multi-stage environments and more.

I've been using Ansible and Ansistrano to deploy a variety of PHP projects - including Drupal 7 & 8, Symfony, Laravel and Sculpin, as well as basic HTML websites, and found it to be very flexible and easy to install and use, and by the end of this talk we will have a fully working deployment playbook, deploying real code onto a real server.

Note that this is focused on PHP applications and Drupal in particular, but applies to any language and CMS or framework.

https://www.oliverdavies.uk/talks/deploying-php-applications-ansible-ansible-vault-ansistrano

## Estimated Duration

40-60 minutes.

## Twitter Handle

@opdavies

**Comment by gundalow** [comment]
@opdavies  We've scheduled the next (virtual) London Meetup for Tuesday 25th of May.
Would you be available to give your talk then?

**Comment by opdavies** [comment]
Yes, that would be great. Thanks!

**Comment by gundalow** [comment]
@opdavies Brilliant, thank you for the quick reply.
We've generally found that 15-30 minute presentations work well, and allow us to have a varied set of content. 
Would that work for you?

**Comment by opdavies** [comment]
30 minutes would work well. I've given the talk before in longer slots but I won't need to explain Ansible itself at an Ansible meetup so I can skip that and focus more on the Ansistrano part. 😃

**Comment by gundalow** [comment]
@opdavies Thank you.
Event created here: https://www.meetup.com/Ansible-London/events/278093392/
1. Could you please email me gundalow at redhat dot com
2. Please share the link

Thanks again

**Comment by gundalow** [comment]
@opdavies Oliver Thank you once again for your great talk.

When you get a chance could you please
1. Raise a PR (Pull Request) to add your slides (PDF or link to external site) into https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2021-05-25
2. Update the README.md to point to the slides (just the filename is fine)
3. Add any links (blog, etc) you think people may find useful into the README.md
4. Send me an email with your postal address and t-shirt size.

**Comment by opdavies** [comment]
PR created - https://github.com/ansible-community/ansible-london-meetup/pull/73.

**Comment by gundalow** [comment]
resolved_by https://github.com/ansible-community/ansible-london-meetup/pull/73

Thank you again for your presentation
