### ISSUE TITLE
Deploying an OpenStack infrastructure on a single server with Ansible

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible-community/ansible-london-meetup#61]
## Talk title
Deploying an OpenStack infrastructure on a single server with Ansible
## Talk Description
This talk will be based on this two part guest blog I wrote for Cumulus Networks: https://cumulusnetworks.com/blog/build-an-openstack-ceph-cluster-with-cumulus-networks-in-gns3-part-1/

In it I will discuss how GNS3 can be used to simulate your entire infrastructure and develop your playbooks, and how an entire highly available OpenStack/Ceph infrastructure can be brought up with virtually no manual intervention through a combination of cloud-init and Ansible. The talk covers a number of important concepts including whitebox switching, network automation with Ansible, building infrastructures, and even how to model an entire infrastructure on a single (albeit powerful) machine for a multitude of purposes including testing and developing Ansible playbooks.

## Estimated Duration
30 mins but can be tailored to the time available.

## Twitter Handle

jamesfreeman959

**Comment by gundalow** [comment]
Hey James, I know it's been many ~months~ years since you kindly offered to present this, though we are planning the next virtual meetup to be on Tuesday 19th April. Would that work?

We will use Matrix for chat, with YouTube (via Jitsi) for the video. We can have a dry-run in advance. It's the same setup we've used for the last few Ansible Contributor Summits.

**Comment by jamesfreeman959** [comment]
Hi John

Great to hear from you and thanks for reaching out - yes absolutely - would love to. Is there an official invite going out, or when should I block my calendar from please? 

Looking forward to it!

James

**Comment by gundalow** [comment]
Hi,
I've just emailed you Jitsi details, did you get it, as well as the invite for Tuesday?

Also, do you already have an account on Matrix?

**Comment by jamesfreeman959** [comment]
Yes all received thanks John and I think I’ve replied to your questions by e-mail. Any issues let me know!

**Comment by gundalow** [comment]
Thanks for the presentation.
Slides can be found at https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2022-04-19
