### ISSUE TITLE
How I migrated from Puppet to Ansible

### ISSUE THREAD

**Issue by dmccuk** [ansible-community/ansible-london-meetup#75]
## Talk title
How I migrated from Puppet to Ansible [or something more snazzy...]

## Talk Description
This talk is about the journey I started a few month ago to migrate a large code base away from puppet and over to Ansible. Highlights include working out an alternative method to hiera (which I feel is actually a pretty good part of puppet) and creating an Ansible workflow to act in a similar way to deliver the correct configuration to the correct servers. My Ansible knowledge has been pushed to the extreme at times but it's only made me see just what Ansible is capable of.

## Estimated Duration
30 minutes

## Twitter Handle
Will complete later

## Sponsorship
It's just me. But happy to put a few quid behind the bar.

**Comment by gundalow** [comment]
Hey Dennis, 

Thank you for the kind offer of the talk. We are planning the next virtual meetup to be on Tuesday 19th April. Would that work?

We will use Matrix for chat, with YouTube (via Jitsi) for the video. We can have a dry-run in advance. It's the same setup we've used for the last few Ansible Contributor Summits.

**Comment by dmccuk** [comment]
Hi John,

That date should be good for me. I'd definitely be up for a practice before hand just to get used to the setup but we can talk about that nearer the time. Let me know what you need from me.

I'm looking forward to it.

**Comment by gundalow** [comment]
Brilliant, I'll drop you an email.

**Comment by dmccuk** [comment]
John,

Just a thought but G-Research wanted me to run my meetup (in-person) at
their Goodge street offices. They have some dates available in the main
room.
I think it would be popular with your members as other meetups are back to
running in person now.

A new lady, Tabitha has taken over (from Jay Tuffnell) the organising of
the meetups if you want to get in touch: ***@***.***

I'd be up for coming in to London for the Ansible meetup.

Regards
Dennis

**Comment by gundalow** [comment]
Hi,
Yup will organize in-person soon.

I've just emailed you Jitsi details, did you get it?

Also do you already have an account on Matrix?

**Comment by gundalow** [comment]
Thanks for the presentation.
Slides can be found at https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2022-04-19
