### ISSUE TITLE
From Zero to Hero: How to build the Ansible Pilot Community

### ISSUE THREAD

**Issue by lucab85** [ansible-community/ansible-london-meetup#81]
## Talk title

From Zero to Hero: How to build the Ansible Pilot Community

## Talk Description

How I share my knowledge and create an Ansible Community by sharing real code examples throw videos and blog articles. Sharing some real use cases, each article shows the status of the system before and after running the code. The Ansible Pilot website has 150K views/month, and the YouTube channel has 26K views/month.

## Estimated Duration

20 minutes

## Twitter Handle

Twitter @ansiblepilot
Website https://www.ansiblepilot.com/

## Sponsorship

It's only me but I'm happy to buy a round of drinks.

**Comment by gundalow** [comment]
@lucab85 Thanks for confirming, we've got you scheduled for the [Monday 23rd September 2024](https://www.meetup.com/ansible-london/events/303113460/) meetup

**Comment by gundalow** [comment]
@lucab85 Thanks again for your presentation.
Could you please upload the PDF of your slides into https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations/2024-09-23 thanks
