### ISSUE TITLE
Should we archive this repo?

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-london-meetup#82]
We are reconsidering how meetups share slides etc. There was a question raised on why we are separating these by geo vs just having one location where meetup organizers can share slides and perhaps reuse parts of other meetup presentations etc.

What are your thoughts on that? Do you want to keep this repository open for future meetups? Are you looking mostly for a place to upload presentations? etc.

**Comment by samccann** [comment]
@gundalow do you have opinions here on whether this is still an active repo for this meetup?

**Comment by gundalow** [comment]
This repo was used to allow people to submit ideas for talks, as well as store links to the [slides and videos](https://github.com/ansible-community/ansible-london-meetup/tree/main/presentations)

**Comment by samccann** [comment]
If it's still going to be used,, then we can close this issue.
