### ISSUE TITLE
IaC - VPS provisioning and configuration on Hetzner Cloud

### ISSUE THREAD

**Issue by dbrennand** [ansible-community/ansible-london-meetup#89]
## Talk title

Infrastructure as Code - VPS provisioning and configuration on Hetzner Cloud.

## Talk Description

On #37, I'd like to submit a talk related to "More Infrastructure as Code".

This talk will a demo on provisioning a VPS using Ansible on Hetzner Cloud and running a basic playbook to configure the VPS post deployment. The demo will use the dynamic inventory plugin from the `hetzner.hcloud` collection too.

## Estimated Duration

20 minutes max.

## Social Media Handle

- https://dbren.uk
- https://github.com/dbrennand
- https://www.linkedin.com/in/dbrenuk

## Sponsorship

None.

**Comment by gundalow** [comment]
@dbrennand Thanks for this talk. Looks great. Nice to see a provision talk not about AWS/K8S.

We might have all the talks for November already, so the following meetup would be Jan/Feb 2025. I'll let you know soon.

**Comment by gundalow** [comment]
@dbrennand The [next meetup is Thursday 21st November](https://www.meetup.com/ansible-london/events/303935960/), would you be interested in giving this talk then?

**Comment by dbrennand** [comment]
Hey @gundalow  - Sorry for the slow response. Yes! I'd love to give the talk then 🙂 - I'm already signed up to attend.

**Comment by dbrennand** [comment]
Presented at the 21st November meetup. [Blog post](https://danielbrennand.com/blog/ansible-meetup-21-november/).
